### ISSUE TITLE
Chrome and detectable

### ISSUE THREAD

**Issue by 7nelas** [SelmiAbderrahim/CreateUndetectableChromeDriver#3]
He is not passing the webdriver test
![image](https://user-images.githubusercontent.com/108302830/176028788-3dc04ae7-339d-4f26-89bd-78bf9bee3d86.png)

**Comment by SelmiAbderrahim** [comment]
Thanks for mentioning that.
Please update to the [latest version](https://pypi.org/project/lucd). 
Then try the debugging option.

```
from lucd.driver import Driver
driver = Driver()
chrome=driver.create_driver(debugging=True)
```
![antibot](https://user-images.githubusercontent.com/65101059/176221419-fe87adfa-db4f-4aa1-9fde-071659f3b5ef.png)
